### PR TITLE
Small addition of GUI tools to create APK

### LINKED ISSUE #156: Add documentation section listing GUI tools alternatives powered by Bubblewrap
Should we create a containerized web app the generates the APK from an online PWA using the bubblewrap CLI tool

### PR DESCRIPTION
**Pull request by amanintech**
Fixes #156 with a small note that refers to PWA Builder

### CODE REVIEW

**Review by andreban — CHANGES_REQUESTED** [review]
Can we move this section to be below the "Community" section?

**Comment by amanintech** [comment]
Done @andreban.

**Review by andreban — APPROVED** [review]
LGTM, Thank you!

**Comment by JudahGabriel** [comment]
Thank you!

**Pull request merged**
