### PR TITLE
Enable a ChromeOS Only Build

### LINKED ISSUE #320: Enable a ChromeOS Only Build
**Is your feature request related to a problem? Please describe.**
If we want to specify that the build should be only for Chrome OS, we would need to add a flag.  This could ensure that app developers only target Chrome OS devices.

**Describe the solution you'd like**
A flag of value specified in the TWAManifest.

**Describe alternatives you've considered**
Manually adding the required uses-feature value to specify Chrome OS only.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by nohe427**
This changes the TWAManifest to specify whether the build should be
designated as a ChromeOS Only package for distribution through Play.
Otherwise, the build will be available to all devices.

Closes #320

### CODE REVIEW

**Comment by nohe427** [comment]
I do have one implementation question.  At the current time, I have to have a user update the isChromeOSOnly flag from the twa-manifest.json file.  Instead, should I add a flag to init and update to specify isChromeOSOnly and update the manifest values accordingly?

Many thanks!

**Comment by andreban** [comment]
We have a few options:

1. Keep as it is (init, modify twa-manifest.json, then run update)
2. Add a flag to init (eg: `--chromeOSOnly` or something)
3. Ask the question to developers during `init`.

I think 2 is fine, but if we expect a large number of developer using ChromeOS only, we should probably implement 3. @PEConn thoughts?

**Review by andreban — APPROVED** [review]
LGTM, Thank you!

**Comment by PEConn** [comment]
Code looks good - I'm wondering if you have a specific app in mind for this though.

**Pull request merged**
