### PR TITLE
Fixes typo in documentation

### PR DESCRIPTION
**Pull request by schalkventer**

### CODE REVIEW

**Comment by andreban** [comment]
@schalkventer Thanks for the PR and happy to merge this, but need the CLA signed before doing it.

**Comment by schalkventer** [comment]
@andreban Not sure why the CLA test fails. I remember doing it before, and when I attempt again I get the following: 
image

**Comment by andreban** [comment]
Thanks for confirming. I forced the CLA bot to run again and it worked. Merging it now.

**Review by andreban — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
