### PR TITLE
Use `fetch-h2` by default with option to fallback to `node-fetch`

### PR DESCRIPTION
**Pull request by andreban**
- `node-fetch` doesn't support HTTP/2 and has had an issue for
  support open since 2017: https://github.com/node-fetch/node-fetch/issues/342
- `fetch-h2` supports HTTP1.1 and HTTP/2 with upgrade.
- Lack of HTTP/2 has been causing issues with developers with server with only HTTP/2 enabled. See #516.
- Changes the code to use `fetch-h2` by default, but allows changing the default from `FetchUtils.setFetchEngine()`.

### CODE REVIEW

**Review by PEConn — APPROVED** [review]
Great, thanks!

**Comment by andreban** [comment]
I'm thinking about using `node-fetch` by default but having a flag that optionally enables `fetch-h2`. @PEConn WDYT?

**Comment by PEConn** [comment]
What's the advantage of supporting both `node-fetch` and `fetch-h2`? Is it just incase `fetch-h2` has some bugs?

**Comment by andreban** [comment]
Yes. `node-fetch` has 21 million downloads / week and `fetch-h2` around 6k.

**Comment by PEConn** [comment]
In that case, I suggest we use `fetch-h2` by default and allow an option to use `node-fetch`. That way we'll know if there are any bugs, and if there aren't we can remove `node-fetch`.

**Review by PEConn — APPROVED** [review]

**Comment by andreban** [comment]
> Aren't we going to make one of them an optional dependency?

I don't think there's a big overhead in having both and this allow deciding which one to use when executing the app. Otherwise, users need to decide at install time.

**Comment by PEConn** [comment]
Gotcha, LGTM

**Pull request merged**
