### PR TITLE
Add themeColorDark aka colorPrimaryDark aka STATUS_BAR_COLOR_DARK

### LINKED ISSUE #802: Override theme color for dark mode
**Is your feature request related to a problem? Please describe.**
The web manifest spec has a known limitation of lacking a way to define a _different_ theme color for when a device is in Dark mode, what causes some weird color matching between app top content and android (e.g) status bar.

**Describe the solution you'd like**
It would be awesome if bubble wrap could provide a way to override the status bar color (or theme color) when the device is in Dark mode.

On the user side, probably adding a `themeColorDark` analogous to the existing `navigationColorDark`.

I'm assuming this should be doable on the generated android code.

**Describe alternatives you've considered**
There are a few ways to supposedly working around this, I could not have any of them to work. I'll briefly list them:

- swapping between two different `<meta name="theme-color"` one for dark and one for light themes
- skip defining a theme color in manifest so the system use the background color of the root element
- somehow loading different manifest for depending on device theme

### PR DESCRIPTION
**Pull request by khmyznikov**
Added customtabs.trusted.STATUS_BAR_COLOR_DARK.

Fixes #802

### CODE REVIEW

**Review by andreban — CHANGES_REQUESTED** [review]
Looking good, thank you for the PR. I dropped a couple request changes to ensure this work with existing TWA Manifests.

**Review by andreban — APPROVED** [review]
LGTM, Thank you very much!

**Comment by khmyznikov** [comment]
@SayedElabady need this in release. I will add integration of new field with PWABuilder.

**Comment by GCSBOSS** [comment]
> @SayedElabady need this in release. I will add integration of new field with PWABuilder.

Waiting to know when this gets releases on PWABuilder /o/

**Comment by andreban** [comment]
@khmyznikov @GCSBOSS This has been deployed on Bubblewrap 1.21.0

**Pull request merged**
