### PR TITLE
Make TWAs use Theme.Translucent.NoTitleBar

### PR DESCRIPTION
**Pull request by EiraGe**
This change is for the android-browser-helper change:
https://github.com/GoogleChrome/android-browser-helper/pull/152

Changes the theme to `Theme.Translucent.NoTitleBar` and removes
`Theme.LauncherActivity` that require `android.appcompat`.

@andreban @PEConn  PTAL Thanks :)

### CODE REVIEW

**Comment by andreban** [comment]
I created a branch on fork that uses a custom build of android-browser-helper, including GoogleChrome/android-browser-helper#152. I'm seeing a reduction of ~700k on apps. The branch is at https://github.com/andreban/llama-pack/tree/appcompat-custom-abh

**Comment by PEConn** [comment]
This is amazing Ella - are we sure there are no visually noticeable effects?

**Comment by andreban** [comment]
> This is amazing Ella - are we sure there are no visually noticeable effects?

I did some tests on an emulator on Friday and and didn't notice anything. Will test on physical devices too.

**Comment by EiraGe** [comment]
I didn't notice any noticeable difference.

I also checked the theme definations and I think the values are mostly the same.
It'd be great if anyone check my math: 
https://android.googlesource.com/platform/frameworks/base.git/+/d24b8183b93e781080b2c16c487e60d51c12da31/core/res/res/values/themes.xml#264

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:appcompat/appcompat/src/main/res/values/themes.xml;l=40

**Pull request merged**
